name: devas
services:
  appserver:
    type: python:3.7
    build_as_root:
      - /app/lando/build_as_root.sh
    build:
      - /app/lando/build.sh
    command:
      - /app/lando/command.sh
    port: 54321
proxy:
  appserver:
    - devas.lndo.site:54321
tooling:
  python:
    service: appserver
    cmd: /usr/local/bin/python
