name: devas-import
services:
  appserver:
    type: python:3.7
    build_as_root:
      - /app/.lando/build_as_root.sh
tooling:
  process:
    service: appserver
    cmd: /app/process_all.py
  python:
    service: appserver
    cmd: /usr/local/bin/python
