---
### Processor configuration

# This file has configuration for closed datasets that were run once.

# This is the base directory for all datasets.
root_dir: /data

# How many data files to process in each batch (default 500).
# batch_size: 500

# The list of datasets to be run by process_all.py.
datasets:
  - name: SuperLIBS 10K Earth
    type: LIBS
    channels: 8767
    averaged: True
    base_dir: SuperLIBS/10K_EARTH
    meta_file: Millennium_COMPS.xlsx
    data_dir: PREPROCESSED_NO_BLR
    log_dir: logs
    output_dir: to-DEVAS
    # output_prefix: prepro_no_blr
    # channels_file: prepro_channels.npy
  - name: SuperLIBS 10K Vacuum
    type: LIBS
    channels: 8767
    averaged: True
    base_dir: SuperLIBS/10K_VACUUM
    meta_file: Millennium_COMPS.xlsx
    data_dir: PREPROCESSED_NO_BLR
    log_dir: logs
    output_dir: to-DEVAS
    # output_prefix: prepro_no_blr
    # channels_file: prepro_channels.npy
  - name: SuperLIBS 10K Mars
    type: LIBS
    channels: 8767
    averaged: True
    base_dir: SuperLIBS/10K_MARS
    meta_file: Millennium_COMPS.xlsx
    data_dir: PREPROCESSED_NO_BLR
    log_dir: logs
    output_dir: to-DEVAS
    # output_prefix: prepro_no_blr
    # channels_file: prepro_channels.npy
  - name: SuperLIBS 18K Mars
    type: LIBS
    channels: 16520
    averaged: True
    base_dir: SuperLIBS/18K_MARS
    meta_file: Millennium_COMPS.xlsx
    data_dir: PREPROCESSED_NO_BLR
    log_dir: logs
    output_dir: to-DEVAS
    # output_prefix: prepro_no_blr
    # channels_file: prepro_channels.npy

### Logging configuration

# Logs will be written to sys.stdout unless you provide a filename.
# Default values are shown below; uncomment and change.
logging:
  # datefmt: '%Y-%m-%d %H:%M:%S'
  # filename: None
  # format: '%(asctime)s - %(levelname)s - %(message)s'
  # level: 'INFO'
